version: '3.3'
services:
    database:
        container_name: test-db
        image: mysql:8
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: testdb
            MYSQL_USER: testuser
            MYSQL_PASSWORD: secret
        networks:
            - test-project

    php:
        container_name: test-php
        build:
          context: .
          dockerfile: ./.docker/php/Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ./login-project:/var/www/html
            - ./json-project:/json-project
        working_dir: /var/www/html
        depends_on: 
            - database
        networks:
            - test-project

    webserver:
        container_name: test-nginx
        image: nginx:alpine
        ports:
            - "8000:80"
        depends_on: 
            - php
        networks:
            - test-project
        working_dir: /var/www/html
        volumes:
            - ./logs/nginx:/var/logs/nginx
            - ./login-project:/var/www/html
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    composer:
      image: composer:latest
      container_name: composer
      volumes:
        - ./login-project:/var/www/html
        - ./json-project:/json-project
      working_dir: /var/www/html
      depends_on:
        - php
      networks:
        - test-project

    node:
      image: node:14-alpine
      container_name: node
      volumes:
        - ./piglatin-project:/app
      working_dir: /app
      networks:
        - test-project

    json:
      container_name: test-json
      image: php:7.4-fpm-alpine
      ports:
        - "9005:8080"
      volumes:
        - ./json-project:/json-project
      working_dir: /json-project
      command: "php -S 0.0.0.0:8080"
      networks:
        - test-project

networks:
    test-project: